apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-statefulset
  labels:
    app: pg-2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pg-2
  template:
    metadata:
      labels:
        app: pg-2
    spec:
      containers:
        - name: pg-2
          image: registry.takima.io/school/proxy/postgres:latest
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: "256M"
              cpu: "100m"
            limits:
              memory: "512M"
              cpu: "1"
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: postgres_password
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: pg-credentials
                  key: postgres_user
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: postgres_db
            - name: PGDATA
              valueFrom:
                configMapKeyRef:
                  name: pg-config
                  key: db_path
          volumeMounts:
            - name: pg-data-statefulset
              mountPath: /var/lib/postgresql/data
      imagePullSecrets:
        - name: takima-school-registry

  volumeClaimTemplates:
    - metadata:
        name: pg-data-statefulset
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
