apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: hello-daemonset
  labels:
    app: hello
spec:
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: registry.takima.io/school/proxy/nginx:1.7.9
